server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        # 响应头过滤器，对输出的响应设置其头部属性名称为X-Response-Default-MyName，值为itcast；如果有多个参数多则重写一行设置不同的参数
        - AddResponseHeader=X-Response-Default-MyName, itcast
      routes:
        # 路由id，可以任意
        - id: user-service-route
          # 代理的服务地址
#          uri: lb://consumer-demo
          uri: http://127.0.0.1:8080
          # 路由断言： 可以匹配映射路径
          predicates:
            - Path=/cf/**
#          filters:
            # 添加请求路径的前缀
            #  - PrefixPath=/user
            # - StripPrefix=1
            # 自定义过滤器
            #- MyParam=name
      globalcors:
        corsConfigurations:
          '[/**]':
            #allowedOrigins: * # 这种写法或者下面的都可以，*表示全部
            allowedOrigins:
              - "http://docs.spring.io"
              - "http://127.0.0.1:8085"
            allowedMethods:
              - GET
              - POST
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    com.netflix: debug
    org.springframework: debug